[project]
name = "stcal"
description = "common tools and algorithms for space telescope calibration pipelines"
readme = "README.md"
requires-python = ">=3.11"
license-files = ["LICENSE"]
authors = [{ name = "STScI" }]
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Astronomy",
]
dependencies = [
  "astropy>=6.0.0",
  "astropy_healpix>=1.1.2",
  "drizzle>=2.2.0,<2.3.0",
  "gwcs>=1.0.1,<2.0.0",
  "numpy>=1.25.0",
  "pyarrow>=10.0.1",
  "requests>=2.22",
  "scikit-image>=0.21.0",
  "scipy>=1.14.1",
  "shapely>=2.1.1",
  "spherical-geometry>=1.3,<1.5",
  "stsci.imagestats>=1.8.3,<1.9",
  "tweakwcs>=0.9,<0.10",
]
dynamic = ["version"]

[project.urls]
documentation = "https://stcal.readthedocs.io"
repository = "https://github.com/spacetelescope/stcal"

[project.optional-dependencies]
contrib = ["ruff", "tox"]
docs = [
  "numpydoc",
  "packaging >=17",
  "sphinx",
  "sphinx-astropy",
  "sphinx-rtd-theme",
  "tomli; python_version <=\"3.11\"",
  "towncrier",
]
test = ["asdf>=3.3.0", "pytest>=9.0", "pytest-doctestplus>=1.3.0"]

[build-system]
requires = [
  "Cython>=0.29.21",
  "numpy>=2.0.0",
  "setuptools>=61",
  "setuptools_scm[toml]>=3.4",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/stcal/_version.py"
version_scheme = "semver-pep440-release-branch"

[tool.setuptools]
zip-safe = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = [
  "astropy.*",
  "gwcs.*",
  "tweakwcs.*",
  "asdf.*",
  "scipy.*",
  "drizzle.*",
  "stsci.imagestats.*",
  "spherical_geometry.*",
  # don't complain about the installed c parts of this library
  "stcal.ramp_fitting.ols_cas22._fit",
  "stcal.ramp_fitting.ols_cas22._jump",
  "stcal.ramp_fitting.slope_fitter",
]
ignore_missing_imports = true

[tool.cython-lint]
max-line-length = 110

[tool.isort]
profile = "black"
filter_files = true
line_length = 110

[tool.codespell]
skip = "*.pdf,*.fits,*.asdf,.tox,build,./tags,.git,docs/_build"
ignore-words-list = "nd, ans, LIK, indx, usig, dne"

[tool.cibuildwheel]
build = "py31*"
skip = "cp3??t-*"  # Disable free-threading builds on all platforms

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]

[tool.coverage.run]
branch = true
parallel = true
source = ["src/", "tests/"]
omit = ["config.py", "config-3.py", "*.rmap"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 50
exclude_also = [
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:",
  "@overload",
  "@typing.overload",
  "class .*\\bProtocol\\):",
  "@(abc\\.)?abstractmethod",
  "raise NotImplementedError",
  "\\.\\.\\.",
]

[tool.cruft]
skip = ["**/__init__.py", "tests/*"]

[tool.numpydoc_validation]
checks = [
  "all",
  "EX01",  # No examples section found
  "SA01",  # See Also section not found
  "ES01",  # No extended summary found
  "GL08",  # Object does not have a docstring. Ruff catches these, and allows more granular ignores.
  "PR01",  # Parameters not documented. Already caught by ruff.
  "PR09",  # Parameter description should finish with a period
  "RT02",  # First line of return should contain only the type
  "RT05",  # Return value description should finish with a period
]

[tool.pytest]
minversion = "9.0"
log_cli_level = "INFO"
xfail_strict = true
doctest_plus = "enabled"
doctest_rst = "enabled"
text_file_format = "rst"
addopts = [
  "--color=yes",
  "--doctest-rst",
  "-ra",
  "--strict-config",
  "--strict-markers",
]
testpaths = ["tests", "src/stcal", "docs"]
norecursedirs = ["benchmarks", ".asv", ".eggs", ".tox", "build", "venv"]
filterwarnings = [
  "error::ResourceWarning",
  # Files left open by tests can trigger ResourceWarnings during test
  # teardown which otherwise would be converted back into a warning
  # by pytest. Turn these PytestUnraisableExceptionWarnings back
  # into errors
  "error::pytest.PytestUnraisableExceptionWarning",
]
markers = ["soctests"]
