name: build

on:
  release:
    types: [ released ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@v1
    with:
      upload_to_pypi: ${{ github.event_name == 'released'}}
      targets: |
        - linux
        - macos
      sdist: true
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}

