name: Ensure changelog

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

# Only cancel in-progress jobs or runs for the current workflow
#   This cancels the already triggered workflows for a specific PR without canceling
#   other instances of this workflow (other PRs, scheduled triggers, etc) when something
#   within that PR re-triggers this CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ensure_changelog:
    name: Verify that a changelog entry exists for this pull request
    runs-on: ubuntu-latest
    steps:
    - uses: scientific-python/action-check-changelogfile@0.2
      env:
        CHANGELOG_FILENAME: CHANGES.rst
        CHECK_MILESTONE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
