name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  PYTHON_VERSIONS: 3.9 3.10 3.11 3.12 3.13 3.14

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3"
      - run: pip install packaging tomli
      - name: convert Python version(s) into JSON list
        id: versions
        shell: python
        run: |
          import os
          import json

          import tomli
          from packaging.specifiers import SpecifierSet
          from packaging.version import Version

          with open("pyproject.toml", "rb") as pyproject_toml_file:
            version_requirements = SpecifierSet(tomli.load(pyproject_toml_file)["project"]["requires-python"])

          versions = [str(version) for version in sorted([Version(version) for version in os.environ["PYTHON_VERSIONS"].split() if version in version_requirements])]

          with open(os.environ["GITHUB_OUTPUT"], "a") as github_output:
              print(f"json={json.dumps(versions)}", file=github_output)
              print(f"oldest={versions[0]}", file=github_output)
              print(f"latest={versions[-1]}", file=github_output)
    outputs:
      python-version-json: ${{ steps.versions.outputs.json }}
      oldest: ${{ steps.versions.outputs.oldest }}
      latest: ${{ steps.versions.outputs.latest }}
  test:
    needs:
      - supported-pythons
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174 # v3.0.1
    with:
      envs: |
        - name: run tests (oldest supported Python, ubuntu-latest)
          linux: py3
          python-version: ${{ needs.supported-pythons.outputs.oldest }}
        - linux: py*
        - name: run tests with coverage (latest supported Python, ubuntu-latest)
          linux: py3-cov
          python-version: ${{ needs.supported-pythons.outputs.latest }}
          pytest-results-summary: true
          coverage: github
        - name: run tests (latest supported Python, macos-latest)
          macos: py3
          python-version: ${{ needs.supported-pythons.outputs.latest }}
      artifact-path: |
        results.xml
