name: extra tests

on:
  pull_request:
    branches:
      - main
      - "*x"
    # To trigger on label changes
    types:
      - synchronize
      - labeled
  schedule:
    # Weekly Monday midnight build
    - cron: "0 0 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: (github.repository == 'spacetelescope/stcal' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@a138926f6e4f9667d1306c24f24f5bdcaa01fbab # v2.5.0
    with:
      envs: |
        - macos: py311-xdist
        - macos: py312-xdist
        - macos: py313-xdist
        - linux: py314-devdeps-xdist
        - macos: py314-devdeps-xdist
